AllCops:
  NewCops: enable
  Exclude:
    - 'lib/generators/**/*'
    - 'db/seeds.rb'

require: rubocop-rails

Style/Documentation:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Security/Open:
  Enabled: false




