services:
  webapp:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      - DATABASE_URL=postgresql://postgres:changeme@db
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - redis
      - db
  db:
    container_name: 'db'
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  pg_data:
  redis_data:
  bundle: