# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe Admin::FormSectionsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # FormSection. As you add validations to FormSection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FormSectionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let(:organization) { FactoryBot.create(:organization) }
  let(:admin) { FactoryBot.create(:user, :admin, organization:) }

  before do
    sign_in(admin)
  end

  describe 'GET #index' do
    it 'returns a success response' do
      FormSection.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      form_section = FormSection.create! valid_attributes
      get :show, params: { id: form_section.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: { form_id: FactoryBot.create(:form, organization:, user: admin) }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      form_section = FormSection.create! valid_attributes
      get :edit, params: { id: form_section.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new FormSection' do
        expect do
          post :create, params: { form_section: valid_attributes }, session: valid_session
        end.to change(FormSection, :count).by(1)
      end

      it 'redirects to the created form_section' do
        post :create, params: { form_section: valid_attributes }, session: valid_session
        expect(response).to redirect_to(FormSection.last)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { form_section: invalid_attributes }, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested form_section' do
        form_section = FormSection.create! valid_attributes
        put :update, params: { id: form_section.to_param, form_section: new_attributes }, session: valid_session
        form_section.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the form_section' do
        form_section = FormSection.create! valid_attributes
        put :update, params: { id: form_section.to_param, form_section: valid_attributes }, session: valid_session
        expect(response).to redirect_to(form_section)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'edit' template)" do
        form_section = FormSection.create! valid_attributes
        put :update, params: { id: form_section.to_param, form_section: invalid_attributes }, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE #destroy' do
    let(:form) { FactoryBot.create(:form, organization:, user: admin) }
    let!(:form_section) { FactoryBot.create(:form_section, form:) }

    before do
      sign_in(admin)
    end

    it 'destroys the requested form_section' do
      expect do
        delete :destroy, params: { form_id: form.short_uuid, id: form_section.to_param }, session: valid_session
      end.to change(FormSection, :count).by(-1)
    end

    context 'with a question' do
      let!(:question) { FactoryBot.create(:question, form:, form_section:) }

      it 'show flash message when trying to delete a form_section that still has questions' do
        expect do
          delete :destroy, params: { form_id: form.short_uuid, id: form_section.to_param }, session: valid_session, format: :js
        end.to change(FormSection, :count).by(0)
        expect(flash[:alert]).to eq('Form section cannot be deleted because it has one or more questions.')
      end
    end

    it 'redirects to the form_sections list' do
      delete :destroy, params: { form_id: form.short_uuid, id: form_section.to_param }, session: valid_session
      expect(response).to redirect_to(admin_form_questions_url)
    end
  end
end
