 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/barriers", type: :request do
  # Barrier. As you add validations to Barrier, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Barrier.create! valid_attributes
      get barriers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      barrier = Barrier.create! valid_attributes
      get barrier_url(barrier)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_barrier_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      barrier = Barrier.create! valid_attributes
      get edit_barrier_url(barrier)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Barrier" do
        expect {
          post barriers_url, params: { barrier: valid_attributes }
        }.to change(Barrier, :count).by(1)
      end

      it "redirects to the created barrier" do
        post barriers_url, params: { barrier: valid_attributes }
        expect(response).to redirect_to(barrier_url(Barrier.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Barrier" do
        expect {
          post barriers_url, params: { barrier: invalid_attributes }
        }.to change(Barrier, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post barriers_url, params: { barrier: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested barrier" do
        barrier = Barrier.create! valid_attributes
        patch barrier_url(barrier), params: { barrier: new_attributes }
        barrier.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the barrier" do
        barrier = Barrier.create! valid_attributes
        patch barrier_url(barrier), params: { barrier: new_attributes }
        barrier.reload
        expect(response).to redirect_to(barrier_url(barrier))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        barrier = Barrier.create! valid_attributes
        patch barrier_url(barrier), params: { barrier: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested barrier" do
      barrier = Barrier.create! valid_attributes
      expect {
        delete barrier_url(barrier)
      }.to change(Barrier, :count).by(-1)
    end

    it "redirects to the barriers list" do
      barrier = Barrier.create! valid_attributes
      delete barrier_url(barrier)
      expect(response).to redirect_to(barriers_url)
    end
  end
end
