 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/milestones", type: :request do
  
  # Milestone. As you add validations to Milestone, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Milestone.create! valid_attributes
      get milestones_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      milestone = Milestone.create! valid_attributes
      get milestone_url(milestone)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_milestone_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      milestone = Milestone.create! valid_attributes
      get edit_milestone_url(milestone)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Milestone" do
        expect {
          post milestones_url, params: { milestone: valid_attributes }
        }.to change(Milestone, :count).by(1)
      end

      it "redirects to the created milestone" do
        post milestones_url, params: { milestone: valid_attributes }
        expect(response).to redirect_to(milestone_url(Milestone.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Milestone" do
        expect {
          post milestones_url, params: { milestone: invalid_attributes }
        }.to change(Milestone, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post milestones_url, params: { milestone: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested milestone" do
        milestone = Milestone.create! valid_attributes
        patch milestone_url(milestone), params: { milestone: new_attributes }
        milestone.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the milestone" do
        milestone = Milestone.create! valid_attributes
        patch milestone_url(milestone), params: { milestone: new_attributes }
        milestone.reload
        expect(response).to redirect_to(milestone_url(milestone))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        milestone = Milestone.create! valid_attributes
        patch milestone_url(milestone), params: { milestone: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested milestone" do
      milestone = Milestone.create! valid_attributes
      expect {
        delete milestone_url(milestone)
      }.to change(Milestone, :count).by(-1)
    end

    it "redirects to the milestones list" do
      milestone = Milestone.create! valid_attributes
      delete milestone_url(milestone)
      expect(response).to redirect_to(milestones_url)
    end
  end
end
