 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/personas", type: :request do
  
  # Persona. As you add validations to Persona, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Persona.create! valid_attributes
      get personas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      persona = Persona.create! valid_attributes
      get persona_url(persona)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_persona_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      persona = Persona.create! valid_attributes
      get edit_persona_url(persona)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Persona" do
        expect {
          post personas_url, params: { persona: valid_attributes }
        }.to change(Persona, :count).by(1)
      end

      it "redirects to the created persona" do
        post personas_url, params: { persona: valid_attributes }
        expect(response).to redirect_to(persona_url(Persona.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Persona" do
        expect {
          post personas_url, params: { persona: invalid_attributes }
        }.to change(Persona, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post personas_url, params: { persona: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested persona" do
        persona = Persona.create! valid_attributes
        patch persona_url(persona), params: { persona: new_attributes }
        persona.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the persona" do
        persona = Persona.create! valid_attributes
        patch persona_url(persona), params: { persona: new_attributes }
        persona.reload
        expect(response).to redirect_to(persona_url(persona))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        persona = Persona.create! valid_attributes
        patch persona_url(persona), params: { persona: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested persona" do
      persona = Persona.create! valid_attributes
      expect {
        delete persona_url(persona)
      }.to change(Persona, :count).by(-1)
    end

    it "redirects to the personas list" do
      persona = Persona.create! valid_attributes
      delete persona_url(persona)
      expect(response).to redirect_to(personas_url)
    end
  end
end
