require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/cscrm_data_collections", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # CscrmDataCollection. As you add validations to CscrmDataCollection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CscrmDataCollection.create! valid_attributes
      get admin_cscrm_data_collections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cscrm_data_collection = CscrmDataCollection.create! valid_attributes
      get admin_cscrm_data_collection_url(cscrm_data_collection)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    let(:user) { FactoryBot.create(:user, :admin) }

    before do
      sign_in(user)
    end

    it "renders a successful response" do
      get new_admin_cscrm_data_collection_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cscrm_data_collection = CscrmDataCollection.create! valid_attributes
      get edit_admin_cscrm_data_collection_url(cscrm_data_collection)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CscrmDataCollection" do
        expect {
          post admin_cscrm_data_collections_url, params: { cscrm_data_collection: valid_attributes }
        }.to change(CscrmDataCollection, :count).by(1)
      end

      it "redirects to the created cscrm_data_collection" do
        post admin_cscrm_data_collections_url, params: { cscrm_data_collection: valid_attributes }
        expect(response).to redirect_to(admin_cscrm_data_collection_url(CscrmDataCollection.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CscrmDataCollection" do
        expect {
          post admin_cscrm_data_collections_url, params: { cscrm_data_collection: invalid_attributes }
        }.to change(CscrmDataCollection, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admin_cscrm_data_collections_url, params: { cscrm_data_collection: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cscrm_data_collection" do
        cscrm_data_collection = CscrmDataCollection.create! valid_attributes
        patch admin_cscrm_data_collection_url(cscrm_data_collection), params: { cscrm_data_collection: new_attributes }
        cscrm_data_collection.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cscrm_data_collection" do
        cscrm_data_collection = CscrmDataCollection.create! valid_attributes
        patch admin_cscrm_data_collection_url(cscrm_data_collection), params: { cscrm_data_collection: new_attributes }
        cscrm_data_collection.reload
        expect(response).to redirect_to(admin_cscrm_data_collection_url(cscrm_data_collection))
      end
    end

    context "with invalid parameters" do

      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cscrm_data_collection = CscrmDataCollection.create! valid_attributes
        patch admin_cscrm_data_collection_url(cscrm_data_collection), params: { cscrm_data_collection: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cscrm_data_collection" do
      cscrm_data_collection = CscrmDataCollection.create! valid_attributes
      expect {
        delete admin_cscrm_data_collection_url(cscrm_data_collection)
      }.to change(CscrmDataCollection, :count).by(-1)
    end

    it "redirects to the cscrm_data_collections list" do
      cscrm_data_collection = CscrmDataCollection.create! valid_attributes
      delete admin_cscrm_data_collection_url(cscrm_data_collection)
      expect(response).to redirect_to(admin_cscrm_data_collections_url)
    end
  end
end
