# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/goal_targets', js: true do
  let(:admin) { FactoryBot.create(:user, :admin) }

  let!(:goal) do
    FactoryBot.create(:goal, organization: admin.organization)
  end

  # GoalTarget. As you add validations to GoalTarget, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      goal_id: goal.id,
    }
  end

  before do
    login_as(admin)
  end

  describe 'GET /index' do
    before do
      visit admin_goal_goal_targets_path(goal)
    end

    it 'renders the index page' do
      expect(page).to have_content('Goal Targets')
      expect(page).to have_link('New Goal Target')
    end

    describe 'navigate to #new' do
      before do
        click_on('New Goal Target')
      end

      it 'renders the new page' do
        expect(page).to have_content('Target date')
      end
    end
  end

  describe 'GET /new' do
    before do
      visit new_admin_goal_goal_target_path(goal)
    end

    describe 'try to create an invalid Goal Target' do
      it 'renders the new page' do
        expect(page).to have_content('Target date')
        fill_in('goal_target_assertion', with: '')
        click_on('Create Goal target')
        expect(page).to have_content("Assertion can't be blank")
      end

      it 'renders the new page' do
        fill_in('goal_target_assertion', with: 'assertion text')
        click_on('Create Goal target')
        expect(page).to have_content('Goal target was successfully created.')
      end
    end
  end
end
