 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/omb_cx_reporting_collections", type: :request do

  # OmbCxReportingCollection. As you add validations to OmbCxReportingCollection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  let(:future_date) {
    Time.now + 3.days
  }

  let(:organization) { FactoryBot.create(:organization) }
  let(:admin) { FactoryBot.create(:user, :admin, organization: organization) }

  before do
    login_as(admin)
  end

  describe "GET /index" do
    it "renders a successful response" do
      OmbCxReportingCollection.create! valid_attributes
      get admin_omb_cx_reporting_collections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      omb_cx_reporting_collection = OmbCxReportingCollection.create! valid_attributes
      get admin_omb_cx_reporting_collection_url(omb_cx_reporting_collection)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_omb_cx_reporting_collection_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      omb_cx_reporting_collection = OmbCxReportingCollection.create! valid_attributes
      get edit_admin_omb_cx_reporting_collection_url(omb_cx_reporting_collection)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OmbCxReportingCollection" do
        expect {
          post admin_omb_cx_reporting_collections_url, params: { omb_cx_reporting_collection: valid_attributes }
        }.to change(OmbCxReportingCollection, :count).by(1)
      end

      it "redirects to the created omb_cx_reporting_collection" do
        post admin_omb_cx_reporting_collections_url, params: { omb_cx_reporting_collection: valid_attributes }
        expect(response).to redirect_to(omb_cx_reporting_collection_url(OmbCxReportingCollection.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OmbCxReportingCollection" do
        expect {
          post admin_omb_cx_reporting_collections_url, params: { omb_cx_reporting_collection: invalid_attributes }
        }.to change(OmbCxReportingCollection, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_omb_cx_reporting_collections_url, params: { omb_cx_reporting_collection: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested omb_cx_reporting_collection" do
        omb_cx_reporting_collection = OmbCxReportingCollection.create! valid_attributes
        patch omb_cx_reporting_collection_url(omb_cx_reporting_collection), params: { omb_cx_reporting_collection: new_attributes }
        omb_cx_reporting_collection.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the omb_cx_reporting_collection" do
        omb_cx_reporting_collection = OmbCxReportingCollection.create! valid_attributes
        patch omb_cx_reporting_collection_url(omb_cx_reporting_collection), params: { omb_cx_reporting_collection: new_attributes }
        omb_cx_reporting_collection.reload
        expect(response).to redirect_to(omb_cx_reporting_collection_url(omb_cx_reporting_collection))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        omb_cx_reporting_collection = OmbCxReportingCollection.create! valid_attributes
        patch omb_cx_reporting_collection_url(omb_cx_reporting_collection), params: { omb_cx_reporting_collection: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested omb_cx_reporting_collection" do
      omb_cx_reporting_collection = OmbCxReportingCollection.create! valid_attributes
      expect {
        delete omb_cx_reporting_collection_url(omb_cx_reporting_collection)
      }.to change(OmbCxReportingCollection, :count).by(-1)
    end

    it "redirects to the omb_cx_reporting_collections list" do
      omb_cx_reporting_collection = OmbCxReportingCollection.create! valid_attributes
      delete omb_cx_reporting_collection_url(omb_cx_reporting_collection)
      expect(response).to redirect_to(omb_cx_reporting_collections_url)
    end
  end
end
