class AddTableComments < ActiveRecord::Migration[7.0]
  def change
    change_table_comment(:service_providers, "A Service Provider, or HISP, as defined in OMB Circular A-11 Section 280")
    change_table_comment(:services, "Services provided by an Agency, often by a Service Provider within an Agency")
    change_table_comment(:service_stages, "A step or stage within a Service, as used in a Business Process Model. eg: start, middle, end")
    change_table_comment(:collections, "Quarterly CX Data Collection")
    change_table_comment(:omb_cx_reporting_collections, "A detailed record belonging to a Collection; a quarterly CX Data Collection")
    change_table_comment(:cscrm_data_collections, "Data Collection for C-SCRM in Q2 of FY 2023")
    change_table_comment(:cscrm_data_collections2, "Data Collection for C-SCRM in Q4 of FY 2023")

    change_column_comment(:services, :id, "Unique identifier for a Service")
    change_column_comment(:services, :service_owner_id, "ID of the User record for which a Service is owned or managed by")
    change_column_comment(:services, :name, "Name of the service")
    change_column_comment(:services, :description, "Description of the designated service")
    change_column_comment(:services, :organization_id, "Unique number for each department. A department may contain several HISPs")
    change_column_comment(:services, :service_provider_id, "Unique number for each Service Provider")
    change_column_comment(:services, :multi_agency_service, "Do multiple agencies collaborate to provide this service?")
    change_column_comment(:services, :multi_agency_explanation, "If applicable, describe how multiple agencies collaborate to provide this service")
    change_column_comment(:services, :justification_text, "HISP provides a description for why this service was selected for priority designation")
    change_column_comment(:services, :contact_center, "True or False for whether the service involves a contact center and/or an interaction with a contact center")
    change_column_comment(:services, :kind, "Identifies the category of service: compliance, administrative, benefits, recreation, informational, data and research, and regulatory")
    change_column_comment(:services, :other_service_type, "")
    change_column_comment(:services, :estimated_annual_volume_of_customers, "Estimated volume of customers on an annual basis")
    change_column_comment(:services, :customer_volume_explanation, "")
    change_column_comment(:services, :digital_service, "Is this a digital service or not?")
    change_column_comment(:services, :fully_digital_service, "Is this a fully digital service or not?")
    change_column_comment(:services, :barriers_to_fully_digital_service, "If applicable, describe the barriers preventing this service from being a fully digital service")
    change_column_comment(:services, :resources_needed_to_provide_digital_service, "If applicable, what resources are needed to provide this service digitally?")
    change_column_comment(:services, :non_digital_explanation, "If applicable, explain why a service is not available via a digital channel")
    change_column_comment(:services, :transactional, "True or False for whether the service is transactional")
    change_column_comment(:services, :where_customers_interact, "Where customers interact")
    change_column_comment(:services, :notes, "Field for HISP to provide additional notes")
    change_column_comment(:services, :hisp, "True or False - Is this Service considered a HISP service?")
    change_column_comment(:services, :department, "Abbreviation of department name")
    change_column_comment(:services, :bureau, "Name of the Bureau to which a service belongs")
    change_column_comment(:services, :bureau_abbreviation, "Abbreviatioon of the Bureau to which a service belongs")
    change_column_comment(:services, :bureau_id, "Reference to the Organization ID that is the Bureau for this Service")
    change_column_comment(:services, :office, "Text description for the office (below a Bureau)")
    change_column_comment(:services, :service_abbreviation, "a unique text string to identify the service")
    change_column_comment(:services, :service_slug, "a unique text string to identify the service")
    change_column_comment(:services, :url, "A website link to their service")
    change_column_comment(:services, :homepage_url, "A primary website link to the service")
    change_column_comment(:services, :channels, "One or more channels where the service is delivered")
    change_column_comment(:services, :service_stages_count, "Helper field that counts how many Service Stages this Service has")
    change_column_comment(:services, :budget_code, "The budget code for this service")
    change_column_comment(:services, :uii_code, "The UII code for this service")
    change_column_comment(:services, :designated_for_improvement_a11_280, "Is this Service designated, per the OMB Circular A-11 Section 280")
    change_column_comment(:services, :aasm_state, "State/status that a Service is in. eg: created, submitted, approved, verified, archived")
  end
end
